name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract ngrok
        run: Expand-Archive -Path ngrok.zip -DestinationPath .

      - name: Verify ngrok Path
        run: dir ngrok.exe

      - name: Enable RDP Service
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-Service -Name TermService -StartupType Automatic
          Start-Service -Name TermService

      - name: Set Runner Password
        run: |
          $password = ConvertTo-SecureString "P@ssw0rd!" -AsPlainText -Force
          Set-LocalUser -Name "runneradmin" -Password $password

      - name: Authenticate ngrok
        run: ./ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Create ngrok Tunnel
        run: ./ngrok.exe tcp 3389

      - name: Print ngrok Tunnels
        run: ./ngrok.exe tunnels

      - name: Debug Logs
        run: |
          Get-Service TermService
          Get-NetFirewallRule -DisplayGroup "Remote Desktop"
          ./ngrok.exe tunnels
