name: Setup ngrok and Expose Port on Windows

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# Define the jobs for this workflow
jobs:
  build:
    # Specify that the job runs on Windows
    runs-on: windows-latest

    # Steps to execute within the job
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Download and install ngrok
      - name: Download ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive -Path ngrok.zip -DestinationPath ngrok
          $env:PATH += ";$PWD/ngrok"

      # Step 3: Set up ngrok with your authtoken (replace with your own token)
      - name: Set up ngrok authtoken
        run: |
          .\ngrok\ngrok authtoken 2sAvueHHgn26Y6IRJx1eNINbnrj_5wFaMLmzZ5QvXr7bc4seF

      # Step 4: Expose a port with ngrok (e.g., port 3389 for RDP or any other port)
      - name: Expose port 3389 (or change the port as needed)
        run: |
     Start-Process -NoNewWindow -FilePath "$PWD/ngrok/ngrok.exe" -ArgumentList "tcp 3389"

      # Step 5: Wait a few seconds for ngrok to establish connection and fetch the public URL
      - name: Get ngrok public URL
        run: |
          Start-Sleep -Seconds 5
          $ngrok_url = (Invoke-RestMethod -Uri http://localhost:4040/api/tunnels).tunnels[0].public_url
          Write-Output "Ngrok is running at $ngrok_url"
