name: Enable RDP and ngrok Tunnel

on:
  push:
    branches:
      - main

jobs:
  RDP:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 1: Set up RDP
      - name: Enable RDP and Configure Firewall
        run: |
          # Enable RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          # Allow RDP through the firewall
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          # Start the RDP service
          Set-Service -Name TermService -StartupType Automatic
          Start-Service -Name TermService

      # Step 2: Download ngrok
      - name: Download ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath .\ngrok

      # Step 3: Authenticate ngrok
      - name: Authenticate ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      # Step 4: Start ngrok Tunnel
      - name: Start ngrok TCP Tunnel
        run: |
          Start-Process -FilePath .\ngrok\ngrok.exe -ArgumentList "tcp 3389" -NoNewWindow -PassThru

      # Step 5: Wait for Tunnel Initialization
      - name: Wait for ngrok Initialization
        run: Start-Sleep -Seconds 10

      # Step 6: Retrieve ngrok Tunnel Info
      - name: Print ngrok Tunnel Info
        run: .\ngrok\ngrok.exe tunnels

      # Step 7: Debugging - Verify RDP Service
      - name: Verify RDP Service
        run: |
          # Confirm RDP service is running
          Get-Service -Name TermService
          # Confirm port 3389 is listening
          netstat -an | findstr "3389"
